export const ff = [
  {
    ProductID: 1,
    ProductName: "Chai",
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: "10 boxes x 20 bags",
    UnitPrice: 18,
    UnitsInStock: 39,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Discontinued: false,
    Category: {
      CategoryID: 1,
      CategoryName: "Beverages",
      Description: "Soft drinks, coffees, teas, beers, and ales",
    },
    FirstOrderedOn: new Date(1996, 8, 20),
  },
  {
    ProductID: 2,
    ProductName: "Chang",
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: "24 - 12 oz bottles",
    UnitPrice: 19,
    UnitsInStock: 17,
    UnitsOnOrder: 40,
    ReorderLevel: 25,
    Discontinued: false,
    Category: {
      CategoryID: 1,
      CategoryName: "Beverages",
      Description: "Soft drinks, coffees, teas, beers, and ales",
    },
    FirstOrderedOn: new Date(1996, 7, 12),
  },
  {
    ProductID: 3,
    ProductName: "Aniseed Syrup",
    SupplierID: 1,
    CategoryID: 2,
    QuantityPerUnit: "12 - 550 ml bottles",
    UnitPrice: 10,
    UnitsInStock: 13,
    UnitsOnOrder: 70,
    ReorderLevel: 25,
    Discontinued: false,
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(1996, 8, 26),
  },
  {
    ProductID: 4,
    ProductName: "Chef Anton's Cajun Seasoning",
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: "48 - 6 oz jars",
    UnitPrice: 22,
    UnitsInStock: 53,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: false,
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(1996, 9, 19),
  },
  {
    ProductID: 5,
    ProductName: "Chef Anton's Gumbo Mix",
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: "36 boxes",
    UnitPrice: 21.35,
    UnitsInStock: 0,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: true,
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(1996, 7, 17),
  },
  {
    ProductID: 6,
    ProductName: "Grandma's Boysenberry Spread",
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: "12 - 8 oz jars",
    UnitPrice: 25,
    UnitsInStock: 120,
    UnitsOnOrder: 0,
    ReorderLevel: 25,
    Discontinued: false,
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(1996, 9, 19),
  },
  {
    ProductID: 7,
    ProductName: "Uncle Bob's Organic Dried Pears",
    SupplierID: 3,
    CategoryID: 7,
    QuantityPerUnit: "12 - 1 lb pkgs.",
    UnitPrice: 30,
    UnitsInStock: 15,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Discontinued: false,
    Category: {
      CategoryID: 7,
      CategoryName: "Produce",
      Description: "Dried fruit and bean curd",
    },
    FirstOrderedOn: new Date(1996, 7, 22),
  },
  {
    ProductID: 8,
    ProductName: "Northwoods Cranberry Sauce",
    SupplierID: 3,
    CategoryID: 2,
    QuantityPerUnit: "12 - 12 oz jars",
    UnitPrice: 40,
    UnitsInStock: 6,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: false,
    Category: {
      CategoryID: 2,
      CategoryName: "Condiments",
      Description: "Sweet and savory sauces, relishes, spreads, and seasonings",
    },
    FirstOrderedOn: new Date(1996, 11, 1),
  },
  {
    ProductID: 9,
    ProductName: "Mishi Kobe Niku",
    SupplierID: 4,
    CategoryID: 6,
    QuantityPerUnit: "18 - 500 g pkgs.",
    UnitPrice: 97,
    UnitsInStock: 29,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: true,
    Category: {
      CategoryID: 6,
      CategoryName: "Meat/Poultry",
      Description: "Prepared meats",
    },
    FirstOrderedOn: new Date(1997, 1, 21),
  },
  {
    ProductID: 10,
    ProductName: "Ikura",
    SupplierID: 4,
    CategoryID: 8,
    QuantityPerUnit: "12 - 200 ml jars",
    UnitPrice: 31,
    UnitsInStock: 31,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: false,
    Category: {
      CategoryID: 8,
      CategoryName: "Seafood",
      Description: "Seaweed and fish",
    },
    FirstOrderedOn: new Date(1996, 8, 5),
  },
];

export const sampleProducts = [
  {
    uid: "PlbQZkrCJucljVEgSjk34uqCPVR2",
    password: "$2a$10$8HDzNx1P0seTlQlwfrMzJOCwikS3zNK3wil4Ct2RNzS/pi0GaRNUe",
    secretKey: "GA4T4JLSERUESW3XNV2DQWRQNRTTUWT2IN2VAT2HIV4HKY2VPA2Q",
    type: "email",
    email: "dummy2@pokerboss.dev",
    status: "active",
    notice: "",
    username: "dummy2@pokerboss.dev",
  },
  {
    uid: "RmNmoqGkyFRjvo2aNWnAq0VrG4t2",
    password: "$2a$10$KI/b2WFkubtmtyKuYCkAAOZ/3J.mFqxrG8yShpCUf9zu3QOZGVRde",
    secretKey: "LZFEMNJUOV2HQUT2M5AEIJDJLNLH2QTDJA7EQKLWEFPHINLZKQYA",
    type: "email",
    email: "dummynew@pokerboss.dev",
    status: "active",
    notice: "",
    username: "dummynew@pokerboss.dev",
  },
  {
    type: "sso:apple",
    "device-id": "FEFB96C8-D858-4652-AC2D-65DD02F388F9",
    email: "jaina.trivedi@in.geekyants.com",
    status: "active",
    notice: "Created new account.",
    "updated-at": {
      _seconds: 1689186421,
      _nanoseconds: 958000000,
    },
    "created-at": {
      _seconds: 1689186421,
      _nanoseconds: 958000000,
    },
  },

  {
    type: "sso:google",
    "device-id": "FEFB96C8-D858-4652-AC2D-65DD02F388F9",
    email: "jaina.trivedi@in.geekyants.com",
    status: "active",
    notice: "Created new account.",
    "updated-at": {
      _seconds: 1689187043,
      _nanoseconds: 582000000,
    },
    "created-at": {
      _seconds: 1689187043,
      _nanoseconds: 582000000,
    },
  },
  {
    uid: "gAQjj3a6dsPorh9l72SzXn2m2323",
    password: "$2a$10$4JJLB0VPfxROR8/1HAJeuOFTw7oCB8gc0cBZNCdaCRKc6mhCKSXi.",
    secretKey: "H5MCM5K5HBJUG32JMI4H2WDYOJKEESJZKBNVITCSFZBHCI2TJIVA",
    type: "email",
    email: "ac@pokerboss.dev",
    status: "active",
    notice: "",
    username: "ac@pokerboss.dev",
  },
  {
    type: "email",
    "device-id": "FEFB96C8-D858-4652-AC2D-65DD02F388F9",
    "2fa": "phone:+919687206884",
    email: "jainatrivedi9@gmail.com",
    status: "2fa-setup",
    "updated-at": {
      _seconds: 1689845554,
      _nanoseconds: 529000000,
    },
    "created-at": {
      _seconds: 1689845554,
      _nanoseconds: 529000000,
    },
  },
  {
    uid: "pp1lyVDjpMMVMysf8OFbQBsdfIJ2",
    password: "$2a$10$x72OWn7rkr.HDhPwsLpQh.RldPo0d4TVRJMBon27jMcBEnY/V4niG",
    secretKey: "GBDXG5RWEU2F4N3HIFNEQR3BHFRDS3CAOJIUOKC3FEWHC5CEJNGA",
    type: "email",
    email: "dummy3@pokerboss.dev",
    status: "active",
    notice: "",
    username: "dummy3@pokerboss.dev",
  },
  {
    uid: "r4YlTL2vGUSLfLFz6p6GC0f3AxE2",
    password: "$2a$10$MP9cxbjf06iPzU.QMn/IReib761Jfw5PDr.d/Vhz9AXboMaI5p8mm",
    secretKey: "MF3G45DVOA7CGRLFMY2F252DMV4FIUKUPFGCGRDPOR2FUXRPM5DQ",
    type: "email",
    email: "aac@pokerboss.dev",
    status: "active",
    notice: "",
    inEdit: false,
    username: "aac@pokerboss.devq",
  },
  {
    uid: "wEzbQgWRVqU7UCUCJRGHhrjZYEc2",
    secretKey: "H5LWK2BDOFBEQ2J4NNEUM332LIYGYWCIMRLEGXJEJ44X2JRVKY5A",
    type: "email",
    email: "aayush@pokerboss.dev",
    status: "active",
    resetOtp: "",
    password: "$2a$10$S/UgKNqCVZOmUxxmk398XO3Tux.LHg8j58p3pxrTgpz/Wgb/mWVOq",
    notice: "",
    inEdit: false,
    username: "aayush@pokerboss.devd",
  },
  {
    password: "$2a$10$2zyhPhXmuKh2CUQBGHcebOIJGQr86w..ZsqoNzzVV1qpU5jJU2E62",
    "secret-key": "K4THOZK5EYYF4ILZOR2HSWCIOBTSQQKEMRYTO6BDLBOUQL2GGE2Q",
    type: "username",
    "device-id": "7ff1f6ae-1b5b-11ee-be56-0242ac120002",
    username: "rajat.pillai",
    status: "active",
    "updated-at": {
      _seconds: 1689769494,
      _nanoseconds: 771000000,
    },
    "created-at": {
      _seconds: 1689769494,
      _nanoseconds: 771000000,
    },
  },
  {
    type: "sso:facebook",
    "device-id": "FEFB96C8-D858-4652-AC2D-65DD02F388F9",
    email: "jaina.trivedi@in.geekyants.com",
    status: "active",
    username: "jaina",
    notice: "Created new account.",
    "updated-at": {
      _seconds: 1689187037,
      _nanoseconds: 914000000,
    },
    "created-at": {
      _seconds: 1689187037,
      _nanoseconds: 914000000,
    },
  },
];
